### ISSUE TITLE
nothing works 👀

### ISSUE THREAD

**Issue by lef-est** [b-yp/logseq-d2#3]
after enabling the plugin, there is no `/d2` command in the slash menu. I tried reloading logseq and disabling & re-enabling the plugin.
manually typing `{{renderer :d2_lang_gkkbq, 100, 200}}` doesn't work either. I get the following error:
![image](https://user-images.githubusercontent.com/9643637/227983266-95e0e676-2fbd-4308-bea0-840500e4d816.png)

There is this error in the console:
![image](https://user-images.githubusercontent.com/9643637/227982231-0e6a6b92-70f4-4ca7-a08f-b0c5dfbdaa8b.png)

**Comment by b-yp** [comment]
I tested on my computer and found that the `/d2` command does exist. I'm not sure what the issue is on your end. If you want to use `{{ renderer :d2_xxx }}` to achieve the function, you need to write the code for d2 in the sub-block. 
For example:

```
- {{ renderder :d2_xxx }}
  - ```d2
    A -> B
    ```
```

**Comment by lef-est** [comment]
thanks for the quick reply. i did write that in the sub-block (and i tried both org-mode code block and markdown's triple ```). the parent block contains `{{renderer :d2_lang_gkkbq, 100, 200}}` but it looks empty in viewing mode.

further info: logseq 0.8.18, windows 10

**Comment by b-yp** [comment]
I'm not sure what the reason is, but I still have a Windows computer at home. I can use it for debugging when I go back at night. Thank you for the information you provided.

**Comment by b-yp** [comment]
> thanks for the quick reply. i did write that in the sub-block (and i tried both org-mode code block and markdown's triple ```). the parent block contains `{{renderer :d2_lang_gkkbq, 100, 200}}` but it looks empty in viewing mode.
> 
> further info: logseq 0.8.18, windows 10

Hello, I have tested it on a Windows computer and it works normally. The slash command `/d2` also takes effect. If it's convenient, would you please record a GIF animation so that I can find the problem faster.

**Comment by lef-est** [comment]
https://user-images.githubusercontent.com/9643637/228414302-bb926ab7-19c1-4461-a712-01f5a9947724.mp4

hope it helps!

**Comment by b-yp** [comment]
> 

I noticed that you are using version `v1.2.0` of the Logseq-d2 plugin, while I have only updated to version `v1.1.0`. I suggest you completely delete the Logseq-d2 plugin and then reinstall it.

For code blocks, only markdown's ``` is currently supported. I will try to support org-mode code blocks in the next version.

**Comment by b-yp** [comment]
As for why you are version `v1.2.0`, I think it may be because I updated a test version when I was testing another implementation method before. Later, there were some problems with that method, so I restored it to the current implementation method. If you have any problems in use, please feel free to raise an issue again.

**Comment by lef-est** [comment]
ahhhhh yes it's working now!! thanks!!
yes i installed it from the marketplace, unlucky timing 😅 glad that i included the plugins panel in my video
